export const REQUESTED_TWEETS = 'REQUESTED_TWEETS'
export const RECEIVED_TWEETS = 'RECEIVED_TWEETS'
export const REQUESTED_TWT_PROFILE = 'REQUESTED_TWT_PROFILE'
export const RECEIVED_TWT_PROFILE = 'RECEIVED_TWT_PROFILE'
export const REQUESTED_TWT_BANNER = 'REQUESTED_TWT_BANNER'
export const RECEIVED_TWT_BANNER = 'RECEIVED_TWT_BANNER'




